/**
 * Shared by the service worker (runtime caching) and the installer
 * (sync.svelte.ts) so both agree on the same cache. The file list and byte
 * sizes live in /pack/manifest.json, generated by scripts/build-content-pack.ts.
 * Bump CONTENT_CACHE only when the generated data changes shape — it
 * re-downloads the entire pack for every user.
 */

export const CONTENT_CACHE = 'content-v2';

export function isContentPath(pathname: string): boolean {
	return pathname.startsWith('/quran/') || pathname.startsWith('/tafsir/');
}

/** Install-time bundles: fetched once by the installer, never cached whole. */
export function isPackPath(pathname: string): boolean {
	return pathname.startsWith('/pack/');
}
